---
title: While True-lus in Python
hero_image: images/banner.png
description: Leer hoe je een oneindige while-lus maakt in Python
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "python"
steps:
  - 
    title: While lussen
