title: Python while loops
hero_image: images/banner.png
description: Using while loops in Python
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "python"
steps:
  - title: While loops
