title: python-while-loop
hero_image: images/banner.png
subtitle: python-while-loop subtitle
description: python-while-loop description
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: cc-prototype
published: false
steps:
  - title: Step one
    duration: 60
