title: While True loop in Python
hero_image: images/banner.png
description: Learn how to create an infinite while loop in Python
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "python"
steps:
  - title: While loops
