---
title: Бесконечный цикл на Python
hero_image: images/banner.png
description: Узнайте, как создать бесконечный цикл while в Python
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "python"
steps:
  - 
    title: Циклы while (пока)
