---
title: Python में While True लूप
hero_image: images/banner.png
description: जानें कि Python में अपरिमित while लूप कैसे बनाएं
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "python"
steps:
  - title: While लूप
