---
title: Bucle While True en Python
hero_image: images/banner.png
description: Aprende cómo crear un bucle infinito en Python
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "python"
steps:
  - 
    title: Bucles While
