---
title: While-True-Schleifen in Python
hero_image: images/banner.png
description: Lerne, wie du eine unendliche While-Schleife in Python erstellst
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "python"
steps:
  - 
    title: While-Schleifen
