---
title: Bucla while True în Python
hero_image: images/banner.png
description: Învață cum să creezi o buclă while infinită în Python
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "python"
steps:
  - 
    title: Bucle while
