---
title: Laço while True em Python
hero_image: images/banner.png
description: Aprenda a criar um laço while infinito em Python
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "python"
steps:
  - 
    title: Laços while
