---
title: Bucle While True en Python
hero_image: images/banner.png
description: Aprende a crear un bucle infinito <0>while</0> en Python
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "python"
steps:
  - 
    title: Bucle while
