---
title: Pętla while True w Pythonie
hero_image: images/banner.png
description: Dowiedz się, jak utworzyć nieskończoną pętlę while w Pythonie
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "python"
steps:
  - 
    title: Pętle while
