---
title: Ciclo While True in Python
hero_image: images/banner.png
description: Impara a creare un ciclo infinito in Python
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "python"
steps:
  - 
    title: Cicli While
